// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("FUGly")>]
[<assembly: AssemblyProductAttribute("FUGly")>]
[<assembly: AssemblyDescriptionAttribute("A test for FUG")>]
[<assembly: AssemblyVersionAttribute("1.0.1")>]
[<assembly: AssemblyFileVersionAttribute("1.0.1")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FUGly"
    let [<Literal>] AssemblyProduct = "FUGly"
    let [<Literal>] AssemblyDescription = "A test for FUG"
    let [<Literal>] AssemblyVersion = "1.0.1"
    let [<Literal>] AssemblyFileVersion = "1.0.1"
    let [<Literal>] AssemblyConfiguration = "Release"
